Support wagtail42
wagtail/wagtail-transfer pull request #144
Opened 2023-02-13 16:24 UTC by nickmoreton

This updates the package for testing against wagtail >= 4.1

Removes:

- Compatibility code and testing for wagtail < v4.1

Updates:

- docs

The test pass locally.

Todo:

- [ ] Test a wagtail 4.1 and 4.2 transfer senario.

2023-02-15 15:43 UTC, victoriachan requested changes
Must be so satisfying! Just a few small points:

1) setup.py needs updating to remove python 3.6 and add python 3.11
2) settings.py: can remove WAGTAIL_COMMENTS_RELATION_NAME?

2023-02-15 15:43 UTC, victoriachan commented on tests/settings.py
>  WAGTAIL_COMMENTS_RELATION_NAME = 'wagtail_admin_comments'
Possiby can remove this too?

2023-02-15 16:14 UTC, nickmoreton commented
> Must be so satisfying!

Yep but with so much to remove you think you have finished and mis a few things.

I have updated the comments thanks.  https://github.com/wagtail/wagtail-transfer/pull/144/commits/791fd2ec796a42078b52e56ad88f8975f590a30d & https://github.com/wagtail/wagtail-transfer/pull/144/commits/7493433a7174eb9fc1d1253137ed8b76fdb49a97

I did a little more adjustment to the Wagtail versions.

2023-02-16 09:11 UTC, victoriachan approved these changes
Looks good!

2023-03-01 09:32 UTC, merged