Support a configurable timeoutfor the API chooser proxy
wagtail/wagtail-transfer pull request #55
Opened 2020-10-02 13:49 UTC by stevejalim

This micro change allows for a more relaxed timeout for the chooser API calls to the source server.

The current default behaviour of 5 seconds is retained, but can be overridden via settings.WAGTAILTRANSFER_CHOOSER_API_PROXY_TIMEOUT

Resolves #53

2020-10-03 08:46 UTC, stevejalim commented
I haven't added the the docs, feeling this is more of a 'private' setting that one would discover only when one needs it, but am happy to document it if you disagree 👍

2020-10-12 11:52 UTC, stevejalim commented
@jacobtoppm If you think this is fine as-is, could it go into the next release, please?

2020-10-12 12:55 UTC, jacobtoppm requested changes
Looks great, but I do think we should document it for the next person who encounters a similar problem.

2020-10-14 13:57 UTC, jacobtoppm approved these changes
LGTM, thanks!

2020-11-06 09:04 UTC, merged